function scr_spr_wm() {
	// Roll
	spr_wm_roll = spr_wethamroll
	spr_w_lonjump = spr_wetham_longjump
    spr_w_lonjump_end = spr_wetham_longjump_loop
	// Doublejump
	spr_wm_djump = spr_wm_walljump
	// Normal
	spr_dressup = spr_pep_palettedressup
	spr_idle = spr_wm_idle  
    spr_move = spr_wm_move  
    spr_land2 = spr_wm_land
    spr_3hpwalk = spr_wm_anger_walk
    spr_3hpidle = spr_wm_anger 
    spr_rageidle = spr_wm_mad
    spr_ragemove = spr_wm_mad_walk
    spr_hurtidle = spr_wm_terror
    spr_hurtwalk = spr_wm_terror_walk 
    spr_panic = spr_wm_panic
    spr_idle1 = spr_wm_idleanim
	spr_idle2 = spr_wm_idleanim2
	spr_idle3 = spr_wm_idleanim3
	spr_idle4 = spr_wm_idleanim4
	spr_idle5 = spr_wm_idleanim5
	spr_idle6 = spr_wm_idleanim6
	spr_frown = spr_player_idlefrown
	spr_freezer = spr_player_freezeridle
	spr_soundtest = spr_wetham_hb
	// Crawl
    spr_crouch = spr_w_crouch
    spr_couchstart = spr_w_crouchstart
    spr_crawl = spr_w_crouchwalk
	// Hurt
    spr_hurt = spr_wm_hurt
    spr_hurtjump = spr_wm_backhurt
	// Jump
    spr_jump = spr_wm_jump
    spr_fall = spr_wm_fall
    spr_land = spr_wm_land
    spr_facestomp = spr_player_facestomp  
    spr_freefall = spr_player_freefall  
    spr_stompprep = spr_wm_mushroombounce
    spr_stomp = spr_wm_stomp_end
	// Level transitions
    spr_lapportal_in = spr_wm_pizzaportalend
    spr_lapportal_out = spr_wm_pizzaportal_out
    spr_entergate = spr_wm_entergate
    spr_lookdoor = spr_wm_enterdoor 
    spr_walkfront = spr_wm_exitdoor
    spr_downpizzabox = spr_wm_downpizzabox
    spr_uppizzabox = spr_wm_uppizzabox
    spr_levelstart = spr_wm_startgate
    spr_victory = spr_wm_treasuredoor
	spr_elevator = spr_peppinoelevator
	spr_spaceship = spr_spacetravelcutscene
	spr_taxi = spr_taxitransition_pep
	spr_taxi_cop = spr_taxitransition_cop
	spr_taxi_pizzatime = spr_taxitransition_pizzaface
	// Ladder
    spr_Ladder = spr_lonewetham_ladder_idle
    spr_laddermove = spr_w_ladder
    spr_ladderdown = spr_w_ladderdown
	// Taunt
    spr_breakdance = spr_player_breakdance  
	spr_taunt = spr_wm_taunt
    spr_supertaunt1 = spr_wm_supertaunt1
    spr_supertaunt2 = spr_wm_supertaunt2
    spr_supertaunt3 = spr_wm_supertaunt3
    spr_supertaunt4 = spr_wm_supertaunt4
    spr_parry1 = spr_wm_parry1
    spr_parry2 = spr_player_parry2  
    spr_parry3 = spr_player_parry3  
	// Mach running
	// - Mach 2 
    spr_mach = spr_wm_attack
	spr_wallsplat = spr_lonewetham_wallsplat
	// - Mach 3
    spr_mach4 = spr_wm_mach3
    spr_mach3jump = spr_wm_dashjump
    spr_hitwall = spr_wm_bump
    spr_dashpadmach = spr_player_dashpad  
	// Wallcling
	spr_wm_cling = spr_wethamcling
	spr_walljumpstart = spr_wethamwalljump
	// Tumble
    spr_dive = spr_wethamdivel
    spr_backslide = spr_lonewetham_tumble_end
    spr_backslideland = spr_lonewetham_tumble
	// Bombdive
	spr_bombdive = spr_player_poundcancel1
	spr_bombdive_land = spr_player_poundcancel2
	// Machdrift
	// - Mach3
    spr_mach3boost = spr_wm_skid
	// Uppercut
    spr_breakdanceuppercut = spr_player_breakdanceuppercut  
    spr_breakdanceuppercutend = spr_player_breakdanceuppercutend  
	// Collect
    spr_gottreasure = spr_wm_treasureget
    spr_keyget = spr_player_keyget  
	// Level gimmicks
	spr_bump = spr_player_bump 
    spr_mrpinch = spr_player_mrpinch  
    spr_rampjump = spr_player_rampjump
	spr_grind = spr_player_grind  
    spr_mach2jump = spr_player_mach2jump  
	spr_superspringplayer = spr_player_presentbox  
    spr_catched = spr_player_catched  
    spr_slipbanan1 = spr_wetham_slip
    spr_slipbanan2 = spr_wetham_crashland
    spr_playercorpsestart = spr_player_corpsestart  
    spr_playercorpsesurf = spr_player_corpsesurf  
	spr_scaredjump1 = spr_player_scaredjump1  
    spr_scaredjump2 = spr_player_scaredjump2  
    spr_currentplayer = spr_player_current  
	spr_throw = spr_player_throw
	spr_grab_ratballoon = spr_player_ratballoon
	spr_trashstart = spr_player_trashstart
	spr_trashjump = spr_player_trashjump
	spr_trashjump2 = spr_player_trashjump2
	spr_trashfall = spr_player_trashfall
	spr_trashslide = spr_player_trashslide
	spr_jetpackstart = spr_player_jetpackstart
	spr_jetpackmid = spr_player_jetpackmid
	spr_jetpackend = spr_player_jetpackend
	// Superjump
    spr_superjump = spr_m_lastbreath 
    spr_superjumpceiling = spr_m_lastbreath_ceiling
	spr_superjumpcancel = spr_m_call
	// Bodyslam
    spr_bodyslamfall = spr_w_groundpound
    spr_bodyslamstart = spr_w_groundpoundstart
    spr_bodyslamland = spr_w_groundpoundland
	// Timesup
    spr_Timesup = spr_wm_timesup 
    spr_deathend = spr_player_deathend  
    spr_dead = spr_player_deathend  
	// Transformations
	// - Animatronic
	spr_stuffed_animatronic = spr_pepanimatronic
	spr_stuffed_debris = spr_animatronicdebris
	// - Pepper Pizza
	spr_poweredup = spr_player_poweredup
    spr_jetpackstart2 = spr_player_jetpackstart2
	spr_firemouthend = spr_player_firemouthend 
	// - Revolver
	spr_pistolintro = spr_player_pistolintro
    spr_pistolshot = spr_player_pistolshot  
	spr_pistolidle = spr_player_pistolidle
    spr_pistolwalk = spr_player_pistolwalk  
	spr_pistoljump = spr_player_pistoljump1
	spr_pistolfall = spr_player_pistoljump2
	spr_pistolland = spr_player_pistolland
	spr_vspistolshot = spr_player_pistolshotend
	spr_vsvigiduel = spr_peppino_duel
	// - Knight
    spr_knightpepwalk = spr_knightpep_walk  
    spr_knightpepjump = spr_knightpep_jump  
    spr_knightpepfall = spr_knightpep_fall  
    spr_knightpepidle = spr_knightpep_idle  
    spr_knightpepjumpstart = spr_knightpep_jumpstart  
    spr_knightpepthunder = spr_knightpep_thunder  
    spr_knightpepland = spr_knightpep_land  
    spr_knightpepdownslope = spr_knightpep_downslope  
    spr_knightpepstart = spr_knightpep_start  
    spr_knightpepcharge = spr_knightpep_charge  
    spr_knightpepdoublejump = spr_knightpep_doublejump  
    spr_knightpepfly = spr_knightpep_fly  
    spr_knightpepdowntrust = spr_knightpep_downtrust  
    spr_knightpepupslope = spr_knightpep_upslope  
    spr_knightpepbump = spr_knightpep_bump  
	// - Fireass
    spr_fireass = spr_player_fireass  
    spr_fireassground = spr_player_fireassground  
	// - Ball
    spr_tumbleend = spr_player_tumbleend  
    spr_tumble = spr_player_tumble  
	// - Doise fight
    spr_stunned = spr_player_stunned  
	// - Clown
    spr_clown = spr_player_clown  
    spr_clownbump = spr_player_clownbump  
    spr_clowncrouch = spr_player_clowncrouch  
    spr_clownfall = spr_player_clownjump  
    spr_clownjump = spr_player_clownjump  
    spr_clownwallclimb = spr_player_clownwallclimb  
	// - Shotgun
    spr_shotgunland = spr_shotgun_land  
    spr_shotgunshoot = spr_player_shotgun  
    spr_shotgunidle = spr_shotgun_idle  
    spr_shotgunwalk = spr_shotgun_walk  
    spr_shotgunfall = spr_shotgun_fall  
    spr_shotgunjump = spr_shotgun_jump  
    spr_shotgunjump1 = spr_player_shotgunjump1  
    spr_shotgunjump2 = spr_player_shotgunjump2  
    spr_shotgunjump3 = spr_player_shotgunjump3  
    spr_shotgunpullout = spr_shotgun_pullout  
    spr_shotgunduck = spr_shotgun_duck  
    spr_shotguncrawl = spr_shotgun_crawl  
    spr_shotgungoduck = spr_shotgun_goduck  
	spr_shotgundrop = spr_shotgunback
	// - Weenie mount
    spr_rideweenie = spr_player_weeniemount  
    spr_weenieturn = spr_player_weenieturn  
	// - Barrel
    spr_barrelidle = spr_player_barrelidle  
    spr_barreljump = spr_player_barreljump  
    spr_barrelroll = spr_player_barrelroll  
    spr_barrelfall = spr_player_barrelfall  
    spr_barrelslipnslide = spr_player_barrelslipnslide  
    spr_barrelmove = spr_player_barrelmove  
    spr_barrelland = spr_player_barrelland  
	// - Firemouth
    spr_firemouthintro = spr_player_firemouthintro   
    spr_firemouth = spr_player_firemouth  
    spr_firemouthspin = spr_player_firemouthspin  
    spr_firemouthdash = spr_player_firemouthdash  
    spr_firemouthidle = spr_player_firemouthidle  
	// - Ghost
    spr_ghostdashright = spr_player_ghostdashright  
    spr_ghostdashdown = spr_player_ghostdashdown  
    spr_ghostdashdownright = spr_player_ghostdashdownright  
    spr_ghostdashup = spr_player_ghostdashup  
    spr_ghostdashupright = spr_player_ghostdashupright  
    spr_ghostidle = spr_player_ghostidle  
    spr_ghostjump = spr_player_ghostjump  
	// - Mort
    spr_mortdoublejumpstart = spr_player_mortdoublejump  
    spr_mortdoublejump = spr_player_mortjump  
    spr_playermortidle = spr_player_mortidle  
    spr_playermortjump = spr_player_mortjump  
    spr_playermortjumpstart = spr_player_mortjumpstart
    spr_playermortland = spr_player_mortland  
    spr_playermortwalk = spr_player_mortwalk  
    spr_mortattackfront = spr_player_mortattackfront  
	spr_mortattackup = spr_player_mortattackup
	spr_mortattackdown = spr_player_mortattackdown
	// - Golf
    spr_golfidle = spr_player_golfidle  
    spr_golfswing = spr_player_golfswing  
	// - Cheeseball
    spr_cheeseballplayer = spr_player_cheeseball  
	// - Boxxed
    spr_boxxedpepintro = spr_boxxedpep_intro  
    spr_boxxedpepidle = spr_boxxedpep_idle  
    spr_boxxedpepwalk = spr_boxxedpep_walk  
    spr_boxxedpepair = spr_boxxedpep_air  
	spr_boxxedpepspin = spr_boxxedpep_spin
	spr_boxxedpepflap = spr_boxxedpep_flap
	// - Cheese monster
    spr_cheesepepidle = spr_cheesepep_idle  
    spr_cheesepepwalk = spr_cheesepep_walk  
    spr_cheesepepjump = spr_cheesepep_jump  
    spr_cheesepepjumpstart = spr_cheesepep_jumpstart  
    spr_cheesepepfall = spr_cheesepep_fall  
    spr_cheesepepland = spr_cheesepep_land  
    spr_cheesepepstickside = spr_cheesepep_stickwall  
	spr_cheesepepwalljump = spr_cheesepep_walljump
	// - Rocket
    spr_rocketstart = spr_player_rocketstart  
    spr_rocket = spr_player_rocket  
    spr_rockethitwall = spr_wetham_stumble
	spr_rocketslide = spr_player_rocketslide
	spr_rocketrun = spr_player_rocketrun
	// Other
    spr_palette = spr_palette_wm
	spr_paletteactor1 = spr_player_idle
	spr_paletteactor2 = spr_player_3hpidle
	spr_paletteactor3 = spr_player_rageidle
	spr_paletteactor4 = spr_player_pistolidle
	spr_paletteactor5 = spr_player_panic
	spr_paletteactor6 = spr_player_smirk
	spr_paletteactor7 = spr_file1
	// - Match
	spr_vstitle = spr_vstitle_player
	spr_vsportrait = spr_vspeppino
	spr_vsportrait_shadow = spr_vspeppinoshadow
	spr_vshealth = spr_bossfight_playerhp
	spr_vshealth_palette = spr_peppalette  
	spr_yellnerves = spr_player_gnomecutscene1
	spr_yellrealize = spr_player_gnomecutscene2
	spr_yellstart = spr_player_gnomecutscene3
	spr_yell = spr_player_gnomecutscene4
	spr_yellend = spr_player_screamtransition
	spr_vshit1 = spr_player_kungfu1
	spr_vshit2 = spr_player_kungfu2
	spr_vshit3 = spr_player_kungfu3
	spr_vshit4 = spr_player_lungehit
	spr_vscloseup = spr_peppino_superattackHUD
	spr_vsvictory = spr_player_levelcomplete
	spr_vsdead1 = spr_player_outofpizza1
	spr_vsdead2 = spr_player_outofpizza2
	spr_vsdead3 = spr_player_outofpizza3
	spr_vsdead4 = spr_player_outofpizza4
	// - Match Noise
	spr_noise_mask = spr_noise_intro1
	spr_noise_mask_out = spr_noise_intro2
    spr_fightball = spr_player_fightball  
	spr_vsnoisefightscream = spr_noise_phasetrans1P
	// - Final Match
	spr_vslookatpizzeria = spr_pepbossintro1
	spr_vslookpizzaface = spr_pepbossintro2
	spr_vspizzaface_intro = spr_pepbossintro3
	spr_vspizzahead_scream = spr_pizzahead_pepintro
	spr_vspizzahead_lunge = spr_player_lunge
	spr_vspizzahead_beatdown1 = spr_pizzahead_beatdown1
	spr_vspizzahead_beatdown2 = spr_pizzahead_beatdown2
	spr_vspizzahead_beatdown3 = spr_pizzahead_beatdown3
	spr_vspizzahead_beatdown4 = spr_pizzahead_beatdown4
	spr_vspizzahead_beatdown5 = spr_pizzahead_beatdown5
	spr_vspizzahead_beatdown6 = spr_pizzahead_beatdown6
	spr_vspizzahead_beatdown7 = spr_pizzahead_beatdown7
	spr_vspizzahead_beatdown8 = spr_pizzahead_beatdown8
	spr_vspizzahead_beatdown9 = spr_pizzahead_beatdown9
	spr_vspizzahead_beatdown10 = spr_pizzahead_beatdown10
	spr_vspizzahead_beatdown11 = spr_pizzahead_beatdown11
	spr_vspizzahead_beatdown12 = spr_pizzahead_beatdown12
	spr_vspizzahead_beatdown13 = spr_pizzahead_beatdown13
	spr_vspizzahead_beatdown14 = spr_pizzahead_beatdown14
	spr_vspizzahead_beatdown15 = spr_pizzahead_beatdown15
	spr_vspizzahead_piledriver = spr_pizzahead_piledriverfinal
	spr_vspizzahead_piledriver_closeup = bg_piledrivercloseshot
	// Prop Mash
    spr_suplexmash1 = spr_player_suplexmash1  
    spr_suplexmash2 = spr_player_suplexmash2  
    spr_suplexmash3 = spr_player_suplexmash3  
    spr_suplexmash4 = spr_player_suplexmash4  
    spr_punch = spr_player_punch  
	spr_suplexmash5 = spr_player_suplexmash5
	spr_suplexmash6 = spr_player_suplexmash6
	spr_suplexmash7 = spr_player_suplexmash7
	// Props
	spr_switch_sign = spr_pepsign
	spr_switch_sleep = spr_peppinoswitch1
	spr_switch_awake = spr_peppinoswitch2
	spr_palettedresser_debris = spr_palettedresserdebris
	spr_pepperman_paiting = spr_pepperman_pepportrait
	spr_grannytv = spr_peppinotvstreet
	
	scr_arc_wmspr()
}