function scr_spr_noise() {
	// Normal
	spr_dressup = spr_playerN_idle
	spr_idle = spr_playerN_idle  
    spr_move = spr_playerN_move  
    spr_land2 = spr_playerN_land2  
    spr_3hpwalk = spr_playerN_angrymove
    spr_3hpidle = spr_playerN_angryidle
    spr_rageidle = spr_playerN_rageidle  
    spr_ragemove = spr_playerN_ragemove  
    spr_hurtidle = spr_playerN_hurtidle  
    spr_hurtwalk = spr_playerN_hurtwalk  
    spr_panic = spr_playerN_panicidle
    spr_idle1 = spr_playerN_idleface
	spr_idle2 = spr_playerN_idlegun
	spr_idle3 = spr_playerN_idlesmoke
	spr_idle4 = spr_playerN_idledance
	spr_idle5 = spr_playerN_idleballoon
	spr_idle6 = spr_playerN_idlemask
    spr_winding = spr_playerN_winding  
	spr_soundtest = spr_noise_vulnerable2
	// Crawl
    spr_crouch = spr_playerN_crouch  
    spr_crouchjump = spr_playerN_crouchjump  
    spr_crouchfall = spr_playerN_crouchfall  
    spr_couchstart = spr_playerN_crouchstart  
    spr_crawl = spr_playerN_crawl  
	// Hurt
    spr_hurt = spr_playerN_hurt  
    spr_hurtjump = spr_playerN_hurtjump
	// Jump
    spr_jump = spr_playerN_jump  
    spr_fall = spr_playerN_fall  
    spr_land = spr_playerN_land  
    spr_facestomp = spr_playerN_machfreefall1
    spr_freefall = spr_playerN_machfreefall2
    spr_stompprep = spr_playerN_stompprep
    spr_stomp = spr_playerN_stomp  
	// Level transitions
    spr_lapportal_in = spr_pizzaportalendN
    spr_lapportal_out = spr_pizzaportalentrancestartN
    spr_entergate = spr_playerN_entergate  
    spr_lookdoor = spr_playerN_lookdoor  
    spr_walkfront = spr_playerN_walkfront  
    spr_downpizzabox = spr_playerN_downpizzabox  
    spr_uppizzabox = spr_playerN_uppizzabox  
    spr_levelstart = spr_playerN_timesup
    spr_victory = spr_playerN_victory  
	spr_elevator = spr_noiseelevator
	spr_spaceship = spr_spacetravelcutsceneN
	spr_taxi = spr_taxitransition_noise
	spr_taxi_cop = spr_taxitransition_copN
	spr_taxi_pizzatime = spr_taxitransition_pizzafaceN
	// Ladder
    spr_Ladder = spr_playerN_ladder  
    spr_laddermove = spr_playerN_laddermove  
    spr_ladderdown = spr_playerN_ladderdown
	// Taunt
    spr_breakdance = spr_playerN_breakdancing
	spr_taunt = spr_playerN_taunt
    spr_supertaunt1 = spr_playerN_supertaunt1  
    spr_supertaunt2 = spr_playerN_supertaunt2  
    spr_supertaunt3 = spr_playerN_supertaunt3  
    spr_supertaunt4 = spr_playerN_supertaunt4  
    spr_parry1 = spr_playerN_parry1  
    spr_parry2 = spr_playerN_parry2  
    spr_parry3 = spr_playerN_parry3  
	// Mach running
	// - Mach 2
    spr_mach1 = spr_playerN_mach1  
    spr_mach = spr_playerN_mach  
    spr_secondjump1 = spr_playerN_secondjump1  
    spr_secondjump2 = spr_playerN_secondjump2  
    spr_wallsplat = spr_playerN_wallsplat 
	// - Mach 3
    spr_mach4 = spr_playerN_mach3
    spr_mach3jump = spr_playerN_mach3jump  
    spr_hitwall = spr_playerN_mach3hitwall  
    spr_mach3hit = spr_playerN_machpunch1
    spr_dashpadmach = spr_playerN_dashpad  
	// - Mach 4
    spr_crazyrun = spr_playerN_crazyrun  
	// Tumble
    spr_dive = spr_playerN_dive  
    spr_machroll = spr_playerN_machroll  
    spr_backslide = spr_playerN_fastroll
    spr_backslideland = spr_playerN_fastroll
    spr_rollgetup = spr_playerN_rollgetup
	// Machdrift
	// - Mach3
    spr_mach3boostfall = spr_playerN_mach3boostfall
    spr_mach3boost = spr_playerN_mach3boost
	// - Mach2
    spr_machslideboostfall = spr_playerN_machslideboostfall  
    spr_machslideboost = spr_playerN_machslideboost  
	// - Breaking
    spr_machslidestart = spr_playerN_machslidestart  
    spr_machslide = spr_playerN_machslide  
    spr_machslideend = spr_playerN_machslideend  
	// Grab dash
    spr_suplexdash = spr_playerN_suplexgrab
    spr_suplexdashjumpstart = spr_playerN_suplexgrabjumpstart  
    spr_suplexdashjump = spr_playerN_suplexgrabjump  
    spr_suplexbump = spr_playerN_suplexbump  
    spr_suplexcancel = spr_playerN_suplexcancel  
	spr_longjump = spr_playerN_longjump  
    spr_longjumpend = spr_playerN_longjumpend   
    spr_crouchslip = spr_playerN_crouchslip  
    spr_piledriver = spr_playerN_piledriver  
    spr_piledriverland = spr_playerN_piledriverland  
    spr_suplexland = spr_playerN_suplexland
    spr_swingding = spr_playerN_swingding  
    spr_swingdingend = spr_playerN_swingdingend  
    spr_haulingjump = spr_playerN_haulingjump  
    spr_haulingidle = spr_playerN_haulingidle  
    spr_haulingwalk = spr_playerN_haulingmove
    spr_haulingstart = spr_playerN_haulingstart  
    spr_haulingfall = spr_playerN_haulingfall  
    spr_haulingland = spr_playerN_haulingland  
	spr_finishingblow1 = spr_playerN_finishingblow1  
    spr_finishingblow2 = spr_playerN_finishingblow2  
    spr_finishingblow3 = spr_playerN_finishingblow3  
    spr_finishingblow4 = spr_playerN_finishingblow4  
    spr_finishingblow5 = spr_playerN_finishingblow5  
	spr_uppercutfinishingblow = spr_playerN_uppercut
	// Uppercut
    spr_breakdanceuppercut = spr_playerN_breakdanceuppercut  
    spr_breakdanceuppercutend = spr_playerN_breakdanceuppercutend  
	// Collect
    spr_gottreasure = spr_playerN_gottreasure  
    spr_keyget = spr_playerN_keyget  
	// Level gimmicks
	spr_bump = spr_playerN_bump 
    spr_mrpinch = spr_playerN_mrpinch  
    spr_rampjump = spr_playerN_rampjump
	spr_grind = spr_playerN_grind  
    spr_mach2jump = spr_playerN_mach2jump  
	spr_superspringplayer = spr_playerN_superspring
    spr_catched = spr_playerN_catched  
    spr_slipbanan1 = spr_playerN_slipbanan1  
    spr_slipbanan2 = spr_playerN_slipbanan2  
    spr_playercorpsestart = spr_playerN_corpsestart  
    spr_playercorpsesurf = spr_playerN_corpsesurf  
	spr_scaredjump1 = spr_playerN_scaredjump1  
    spr_scaredjump2 = spr_playerN_scaredjump2  
    spr_currentplayer = spr_playerN_current  
	// spr_grab_ratballoon = spr_playerN_ratballoonfall
	// spr_grab_ratballoon_flap = spr_playerN_ratballoonfloat
	// spr_trashjump = spr_playerN_trash
	// Superjump
    spr_superjumpprep = spr_playerN_Sjumpstart 
    spr_superjump = spr_playerN_Sjump  
    spr_superjumppreplight = spr_playerN_Sjumpprep
    spr_superjumpright = spr_playerN_Sjumpmoveright  
    spr_superjumpleft = spr_playerN_Sjumpmoveleft 
    spr_superjumpland = spr_playerN_Sjumpland 
    spr_machfreefall = spr_playerN_fall
	// Bodyslam
    spr_bodyslamfall = spr_playerN_bodyslam
    spr_bodyslamstart = spr_playerN_bodyslamstart  
    spr_bodyslamland = spr_playerN_bodyslamland  
    spr_facehurtup = spr_playerN_facehurtup  
    spr_facehurt = spr_playerN_facehurt  
	// Timesup
    spr_Timesup = spr_playerN_timesup  
    spr_deathend = spr_playerN_deathend  
    spr_dead = spr_playerN_deathend  
	// Transformations
	// - Animatronic
	spr_stuffed_animatronic = spr_pepanimatronic
	spr_stuffed_debris = spr_animatronicdebris
	// - Pepper Pizza
	spr_poweredup = spr_playerN_pizzapepper
    spr_jetpackstart2 = spr_playerN_noisebombspinjump
	spr_firemouthend = spr_playerN_firemouthend  
	// - Knight
    spr_knightpepwalk = spr_playerN_knightmove
    spr_knightpepjump = spr_playerN_knightjump
    spr_knightpepfall = spr_playerN_knightfall
    spr_knightpepidle = spr_playerN_knightidle
    spr_knightpepjumpstart = spr_playerN_knightjumpstart
    spr_knightpepthunder = spr_playerN_knightstart
    spr_knightpepland = spr_playerN_knightland 
    spr_knightpepdownslope = spr_playerN_knightdownslope
    spr_knightpepstart = spr_playerN_knightsword
    spr_knightpepcharge = spr_playerN_knightslide
    spr_knightpepdoublejump = spr_playerN_knightdoublejumpfall
    spr_knightpepfly = spr_playerN_knightfly
    spr_knightpepdowntrust = spr_playerN_knightdowntrust
    spr_knightpepupslope = spr_playerN_knightslideup
    spr_knightpepbump = spr_playerN_knightgroundbump
	// - Fireass
    spr_fireass = spr_playerN_fireass  
    spr_fireassground = spr_playerN_fireassground  
	// - Ball
    spr_tumbleend = spr_playerN_tumbleend  
    spr_tumble = spr_playerN_tumble  
	// - Doise fight
    spr_stunned = spr_playerN_stunned  
	// - Clown
    spr_clown = spr_playerN_clown  
    spr_clownbump = spr_playerN_clownbump  
    spr_clowncrouch = spr_playerN_clowncrouch  
    spr_clownfall = spr_playerN_clownjump  
    spr_clownjump = spr_playerN_clownjump  
    spr_clownwallclimb = spr_playerN_clownwallclimb  
	// - Shotgun
    spr_shotgunland = spr_playerN_minigunland
    spr_shotgunshoot = spr_playerN_minigunshoot
    spr_shotgunidle = spr_playerN_minigunidle
    spr_shotgunwalk = spr_playerN_minigunmove
    spr_shotgunfall = spr_playerN_minigunfall
    spr_shotgunjump = spr_playerN_minigunjump
    spr_shotgunjump1 = spr_playerN_minigunslamprep
	// spr_shotgunjump1end = spr_playerN_minigunslamprep
    spr_shotgunjump2 = spr_playerN_minigunslamland
    spr_shotgunjump3 = spr_playerN_minigunslam
    spr_shotgunpullout = spr_playerN_minigunstart
    spr_shotgunduck = spr_playerN_minigunduck
    spr_shotguncrawl = spr_playerN_miniguncrawl
    spr_shotgungoduck = spr_playerN_minigungoduck
	spr_shotgundrop = spr_minigunfall
	// - Weenie mount
    spr_rideweenie = spr_playerN_weeniemount  
    spr_weenieturn = spr_playerN_weenieturn  
	// - Barrel
    spr_barrelidle = spr_playerN_barrelidle  
    spr_barreljump = spr_playerN_barreljump  
    spr_barrelroll = spr_playerN_barrelroll  
    spr_barrelfall = spr_playerN_barrelfall  
    spr_barrelslipnslide = spr_playerN_barrelslipnslide  
    spr_barrelmove = spr_playerN_barrelmove  
    spr_barrelland = spr_playerN_barrelland  
	// - Firemouth
    spr_firemouthintro = spr_playerN_firemouthintro  
    spr_firemouth = spr_playerN_firemouth  
    spr_firemouthspin = spr_playerN_firemouthspin  
    spr_firemouthdash = spr_playerN_firemouthdash  
    spr_firemouthidle = spr_playerN_firemouthidle  
	// - Ghost
    spr_ghostdashright = spr_playerN_ghostdash
    spr_ghostdashdown = spr_playerN_ghostdashdown  
    spr_ghostdashdownright = spr_playerN_ghostdashdownright  
    spr_ghostdashup = spr_playerN_ghostdashup  
    spr_ghostdashupright = spr_playerN_ghostdashupright  
    spr_ghostidle = spr_playerN_ghostidle  
    spr_ghostjump = spr_playerN_ghostjump  
	// - Mort
    spr_mortdoublejumpstart = spr_playerN_mortdoublejump  
    spr_mortdoublejump = spr_playerN_mortjump  
    spr_playermortidle = spr_playerN_mortidle  
    spr_playermortjump = spr_playerN_mortjump  
    spr_playermortjumpstart = spr_playerN_mortjumpstart
    spr_playermortland = spr_playerN_mortland  
    spr_playermortwalk = spr_playerN_mortwalk  
	// spr_playermortthrow = spr_playerN_mortthrow
	// - Golf
    spr_golfidle = spr_playerN_golfidle  
    spr_golfswing = spr_playerN_golfswing  
	// - Cheeseball
    spr_cheeseballplayer = spr_playerN_cheeseball  
	// - Boxxed
    spr_boxxedpepintro = spr_playerN_boxxedintro
    spr_boxxedpepidle = spr_playerN_boxxedidle
    spr_boxxedpepwalk = spr_playerN_boxxedmove
	spr_boxxedpepjump = spr_playerN_boxxedjump
    spr_boxxedpepair = spr_playerN_boxxedfall
	spr_boxxedpepdash = spr_playerN_boxxedhit
	spr_boxxedpepdashend = spr_playerN_boxxedhit
	spr_boxxedpepspin = spr_playerN_boxxedhit
	spr_boxxedpepflap = spr_playerN_boxxedjetpack
	spr_boxxedpepflapend = spr_playerN_boxxedjetpackfall
	// - Cheese monster
    spr_cheesepepidle = spr_playerN_cheesedidle
    spr_cheesepepwalk = spr_playerN_cheesedmove
    spr_cheesepepjump = spr_playerN_cheesedjump
    spr_cheesepepjumpstart = spr_playerN_cheesedjumpstart
    spr_cheesepepfall = spr_playerN_cheesedfall
    spr_cheesepepland = spr_playerN_cheesedland
    spr_cheesepepstickside = spr_playerN_cheesedstickside
	spr_cheesepepwalljump = spr_playerN_cheesedwalljump
	// - Rocket
    spr_rocketstart = spr_playerN_rocketstart  
    spr_rocket = spr_playerN_rocket  
    spr_rockethitwall = spr_playerN_rockethitwall  
	// Other
    spr_palette = spr_noisepalette
	spr_paletteactor1 = spr_playerN_idle
	spr_paletteactor2 = spr_playerN_idlesmoke
	spr_paletteactor3 = spr_playerN_rageidle
	spr_paletteactor4 = spr_playerN_hurtidle
	spr_paletteactor5 = spr_playerN_breakdancing
	spr_paletteactor6 = spr_playerN_panicidle
	spr_paletteactor7 = spr_noise_vulnerable2
	// - Match
	spr_vstitle = spr_vstitle_playerN
	spr_vsportrait = spr_vsnoiseplayer
	spr_vsportrait_shadow = spr_vsnoiseplayershadow
	spr_vshealth = spr_bossfight_noiseHP
	spr_vshealth_palette = spr_noisepalette
	spr_yellnerves = spr_player_gnomecutscene1
	spr_yellrealize = spr_player_gnomecutscene2
	spr_yellstart = spr_player_gnomecutscene3
	spr_yell = spr_player_gnomecutscene4
	spr_yellend = spr_player_screamtransition
	spr_vshit1 = spr_playerN_tackle
	spr_vshit2 = spr_playerN_tackle
	spr_vshit3 = spr_playerN_backkick
	spr_vshit4 = spr_playerN_backkick
	spr_vscloseup = spr_noise_superattackHUD
	// spr_vsmock = spr_playerN_bosstransition
	spr_vsvictory = spr_playerN_levelcomplete
	// spr_vsdead1 = spr_playerN_bossdeath1
	// spr_vsdead2 = spr_playerN_bossdeath2
	// - Match Doise
	spr_noise_mask = spr_noise_intro1
	spr_noise_mask_out = spr_noise_intro2
    spr_fightball = spr_player_fightball  
	spr_vsnoisefightscream = spr_noise_phasetrans1P
	// - Final Match
	spr_vslookatpizzeria = spr_pepbossintro1
	spr_vslookpizzaface = spr_pepbossintro2
	spr_vspizzaface_intro = spr_pepbossintro3
	spr_vspizzahead_scream = spr_pizzahead_pepintro
	spr_vspizzahead_lunge = spr_player_lunge
	spr_vspizzahead_beatdown1 = spr_pizzahead_beatdown1
	spr_vspizzahead_beatdown2 = spr_pizzahead_beatdown2
	spr_vspizzahead_beatdown3 = spr_pizzahead_beatdown3
	spr_vspizzahead_beatdown4 = spr_pizzahead_beatdown4
	spr_vspizzahead_beatdown5 = spr_pizzahead_beatdown5
	spr_vspizzahead_beatdown6 = spr_pizzahead_beatdown6
	spr_vspizzahead_beatdown7 = spr_pizzahead_beatdown7 
	spr_vspizzahead_beatdown8 = spr_pizzahead_beatdown8
	spr_vspizzahead_beatdown9 = spr_pizzahead_beatdown9
	spr_vspizzahead_beatdown10 = spr_pizzahead_beatdown10
	spr_vspizzahead_beatdown11 = spr_pizzahead_beatdown11
	spr_vspizzahead_beatdown12 = spr_pizzahead_beatdown12
	spr_vspizzahead_beatdown13 = spr_pizzahead_beatdown13
	spr_vspizzahead_beatdown14 = spr_pizzahead_beatdown14
	spr_vspizzahead_beatdown15 = spr_pizzahead_beatdown15
	spr_vspizzahead_piledriver = spr_pizzahead_piledriverfinal
	spr_vspizzahead_piledriver_closeup = bg_piledrivercloseshot
	// Prop Mash
    spr_suplexmash1 = spr_playerN_suplexmash1  
    spr_suplexmash2 = spr_playerN_suplexmash2  
    spr_suplexmash3 = spr_playerN_suplexmash3  
    spr_suplexmash4 = spr_playerN_suplexmash4  
    spr_punch = spr_playerN_punch  
	spr_suplexmash5 = spr_player_suplexmash5
	spr_suplexmash6 = spr_player_suplexmash6
	spr_suplexmash7 = spr_player_suplexmash7
	// Props
	spr_switch_sign = spr_noisesign
	spr_switch_sleep = spr_peppinoswitch1
	spr_switch_awake = spr_peppinoswitch2
	spr_palettedresser_debris = spr_palettedresserdebrisN
	spr_pepperman_paiting = spr_pepperman_noiseportrait
	spr_grannytv = spr_noisetvstreet
}